apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-deployer
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-deployer-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: github-actions-deployer
type: kubernetes.io/service-account-token